---
workspace:
    dataset: '~/face-club/dataset/'
    model: '~/face-club/model/'
    images: '~/face-club/images/'
database:
    external:
        config: '~/face-club/database.yaml'
        enable: true
    internal:
        url: 'sqlite:///db/face.db'
logging:
    path: 'log'