---
workspace:
    dataset: '~/face-club/dataset/'
database:
    external:
        config: '~/face-club/database.yaml'
        enable: false
    internal:
        url: 'sqlite:///~/db/face.db'
logging:
    path: 'log'